/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gdmnftSol from "./GDMNFT.sol";
export type { gdmnftSol };
import type * as rgdnftSol from "./RGDNFT.sol";
export type { rgdnftSol };
export type { SGDNFT } from "./SGDNFT";
