/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gdmnftSol from "./GDMNFT.sol";
export type { gdmnftSol };
export type { RGDNFT } from "./RGDNFT";
export type { SGDNFT } from "./SGDNFT";
