/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGDMRegistry,
  IGDMRegistryInterface,
} from "../../../contracts/RGDNFT.sol/IGDMRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "rgdTokenId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "sequencingInfo",
        type: "string",
      },
    ],
    name: "getPipelineStatus",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGDMRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IGDMRegistryInterface {
    return new Interface(_abi) as IGDMRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGDMRegistry {
    return new Contract(address, _abi, runner) as unknown as IGDMRegistry;
  }
}
