/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGDMRegistry__factory } from "./IGDMRegistry__factory";
export { RGDNFT__factory } from "./RGDNFT__factory";
