/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gdmnftSol from "./GDMNFT.sol";
export { RGDNFT__factory } from "./RGDNFT__factory";
export { SGDNFT__factory } from "./SGDNFT__factory";
