/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gdmnftSol from "./GDMNFT.sol";
export * as rgdnftSol from "./RGDNFT.sol";
export { SGDNFT__factory } from "./SGDNFT__factory";
