/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace GDMRegistry {
  export type SGDRecordStruct = {
    tokenId: BigNumberish;
    sgdId: string;
    rgdId: string;
    cid: string;
    registeredOwner: AddressLike;
    accessCondition: string;
    price: BigNumberish;
    collectionDate: BigNumberish;
    sampleType: string;
    patientRef: string;
    consentCode: string;
    sampleHash: string;
    encryptionScheme: string;
    sequencingInfo: string;
    signatureRef: string;
    encHash: string;
    createdAt: BigNumberish;
    active: boolean;
  };

  export type SGDRecordStructOutput = [
    tokenId: bigint,
    sgdId: string,
    rgdId: string,
    cid: string,
    registeredOwner: string,
    accessCondition: string,
    price: bigint,
    collectionDate: bigint,
    sampleType: string,
    patientRef: string,
    consentCode: string,
    sampleHash: string,
    encryptionScheme: string,
    sequencingInfo: string,
    signatureRef: string,
    encHash: string,
    createdAt: bigint,
    active: boolean
  ] & {
    tokenId: bigint;
    sgdId: string;
    rgdId: string;
    cid: string;
    registeredOwner: string;
    accessCondition: string;
    price: bigint;
    collectionDate: bigint;
    sampleType: string;
    patientRef: string;
    consentCode: string;
    sampleHash: string;
    encryptionScheme: string;
    sequencingInfo: string;
    signatureRef: string;
    encHash: string;
    createdAt: bigint;
    active: boolean;
  };

  export type PublicRecordStruct = {
    tokenId: BigNumberish;
    sgdId: string;
    rgdId: string;
    currentOwner: AddressLike;
    accessCondition: string;
    price: BigNumberish;
    collectionDate: BigNumberish;
    sampleType: string;
    patientRef: string;
    consentCode: string;
    sampleHash: string;
    encryptionScheme: string;
    sequencingInfo: string;
    active: boolean;
  };

  export type PublicRecordStructOutput = [
    tokenId: bigint,
    sgdId: string,
    rgdId: string,
    currentOwner: string,
    accessCondition: string,
    price: bigint,
    collectionDate: bigint,
    sampleType: string,
    patientRef: string,
    consentCode: string,
    sampleHash: string,
    encryptionScheme: string,
    sequencingInfo: string,
    active: boolean
  ] & {
    tokenId: bigint;
    sgdId: string;
    rgdId: string;
    currentOwner: string;
    accessCondition: string;
    price: bigint;
    collectionDate: bigint;
    sampleType: string;
    patientRef: string;
    consentCode: string;
    sampleHash: string;
    encryptionScheme: string;
    sequencingInfo: string;
    active: boolean;
  };

  export type RegisterInputStruct = {
    initialOwner: AddressLike;
    sgdId: string;
    rgdId: string;
    cid: string;
    accessCondition: string;
    price: BigNumberish;
    collectionDate: BigNumberish;
    sampleType: string;
    patientRef: string;
    consentCode: string;
    sampleHash: string;
    encryptionScheme: string;
    sequencingInfo: string;
    signatureRef: string;
    encHash: string;
    tokenURI: string;
  };

  export type RegisterInputStructOutput = [
    initialOwner: string,
    sgdId: string,
    rgdId: string,
    cid: string,
    accessCondition: string,
    price: bigint,
    collectionDate: bigint,
    sampleType: string,
    patientRef: string,
    consentCode: string,
    sampleHash: string,
    encryptionScheme: string,
    sequencingInfo: string,
    signatureRef: string,
    encHash: string,
    tokenURI: string
  ] & {
    initialOwner: string;
    sgdId: string;
    rgdId: string;
    cid: string;
    accessCondition: string;
    price: bigint;
    collectionDate: bigint;
    sampleType: string;
    patientRef: string;
    consentCode: string;
    sampleHash: string;
    encryptionScheme: string;
    sequencingInfo: string;
    signatureRef: string;
    encHash: string;
    tokenURI: string;
  };
}

export interface GDMRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateSGD"
      | "getCID"
      | "getFullRecord"
      | "getPublicRecord"
      | "hasPurchased"
      | "nextTokenId"
      | "owner"
      | "purchaseFullAccess"
      | "registerSGD"
      | "registrar"
      | "renounceOwnership"
      | "setAccessCondition"
      | "setPrice"
      | "setRegistrar"
      | "sgdNft"
      | "transferOwnership"
      | "updateCID"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessConditionUpdated"
      | "CIDUpdated"
      | "FullAccessPurchased"
      | "OwnershipTransferred"
      | "PriceUpdated"
      | "RegistrarUpdated"
      | "SGDDeactivated"
      | "SGDRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateSGD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCID",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFullRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPurchased",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseFullAccess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSGD",
    values: [GDMRegistry.RegisterInputStruct]
  ): string;
  encodeFunctionData(functionFragment: "registrar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAccessCondition",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistrar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "sgdNft", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCID",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivateSGD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFullRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseFullAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSGD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registrar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAccessCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sgdNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateCID", data: BytesLike): Result;
}

export namespace AccessConditionUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, newCondition: string];
  export type OutputTuple = [tokenId: bigint, newCondition: string];
  export interface OutputObject {
    tokenId: bigint;
    newCondition: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CIDUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, newCid: string];
  export type OutputTuple = [tokenId: bigint, newCid: string];
  export interface OutputObject {
    tokenId: bigint;
    newCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FullAccessPurchasedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, buyer: string, amount: bigint];
  export interface OutputObject {
    tokenId: bigint;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [tokenId: bigint, newPrice: bigint];
  export interface OutputObject {
    tokenId: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistrarUpdatedEvent {
  export type InputTuple = [newRegistrar: AddressLike];
  export type OutputTuple = [newRegistrar: string];
  export interface OutputObject {
    newRegistrar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SGDDeactivatedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SGDRegisteredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    initialOwner: AddressLike,
    sgdId: string,
    cid: string,
    price: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    initialOwner: string,
    sgdId: string,
    cid: string,
    price: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    initialOwner: string;
    sgdId: string;
    cid: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GDMRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): GDMRegistry;
  waitForDeployment(): Promise<this>;

  interface: GDMRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateSGD: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCID: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getFullRecord: TypedContractMethod<
    [tokenId: BigNumberish],
    [GDMRegistry.SGDRecordStructOutput],
    "view"
  >;

  getPublicRecord: TypedContractMethod<
    [tokenId: BigNumberish],
    [GDMRegistry.PublicRecordStructOutput],
    "view"
  >;

  hasPurchased: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  nextTokenId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  purchaseFullAccess: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "payable"
  >;

  registerSGD: TypedContractMethod<
    [input: GDMRegistry.RegisterInputStruct],
    [bigint],
    "nonpayable"
  >;

  registrar: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAccessCondition: TypedContractMethod<
    [tokenId: BigNumberish, newCondition: string],
    [void],
    "nonpayable"
  >;

  setPrice: TypedContractMethod<
    [tokenId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRegistrar: TypedContractMethod<
    [newRegistrar: AddressLike],
    [void],
    "nonpayable"
  >;

  sgdNft: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCID: TypedContractMethod<
    [tokenId: BigNumberish, newCid: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateSGD"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCID"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getFullRecord"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [GDMRegistry.SGDRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPublicRecord"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [GDMRegistry.PublicRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPurchased"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextTokenId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseFullAccess"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "registerSGD"
  ): TypedContractMethod<
    [input: GDMRegistry.RegisterInputStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registrar"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAccessCondition"
  ): TypedContractMethod<
    [tokenId: BigNumberish, newCondition: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<
    [tokenId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRegistrar"
  ): TypedContractMethod<[newRegistrar: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sgdNft"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCID"
  ): TypedContractMethod<
    [tokenId: BigNumberish, newCid: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AccessConditionUpdated"
  ): TypedContractEvent<
    AccessConditionUpdatedEvent.InputTuple,
    AccessConditionUpdatedEvent.OutputTuple,
    AccessConditionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CIDUpdated"
  ): TypedContractEvent<
    CIDUpdatedEvent.InputTuple,
    CIDUpdatedEvent.OutputTuple,
    CIDUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FullAccessPurchased"
  ): TypedContractEvent<
    FullAccessPurchasedEvent.InputTuple,
    FullAccessPurchasedEvent.OutputTuple,
    FullAccessPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RegistrarUpdated"
  ): TypedContractEvent<
    RegistrarUpdatedEvent.InputTuple,
    RegistrarUpdatedEvent.OutputTuple,
    RegistrarUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SGDDeactivated"
  ): TypedContractEvent<
    SGDDeactivatedEvent.InputTuple,
    SGDDeactivatedEvent.OutputTuple,
    SGDDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "SGDRegistered"
  ): TypedContractEvent<
    SGDRegisteredEvent.InputTuple,
    SGDRegisteredEvent.OutputTuple,
    SGDRegisteredEvent.OutputObject
  >;

  filters: {
    "AccessConditionUpdated(uint256,string)": TypedContractEvent<
      AccessConditionUpdatedEvent.InputTuple,
      AccessConditionUpdatedEvent.OutputTuple,
      AccessConditionUpdatedEvent.OutputObject
    >;
    AccessConditionUpdated: TypedContractEvent<
      AccessConditionUpdatedEvent.InputTuple,
      AccessConditionUpdatedEvent.OutputTuple,
      AccessConditionUpdatedEvent.OutputObject
    >;

    "CIDUpdated(uint256,string)": TypedContractEvent<
      CIDUpdatedEvent.InputTuple,
      CIDUpdatedEvent.OutputTuple,
      CIDUpdatedEvent.OutputObject
    >;
    CIDUpdated: TypedContractEvent<
      CIDUpdatedEvent.InputTuple,
      CIDUpdatedEvent.OutputTuple,
      CIDUpdatedEvent.OutputObject
    >;

    "FullAccessPurchased(uint256,address,uint256)": TypedContractEvent<
      FullAccessPurchasedEvent.InputTuple,
      FullAccessPurchasedEvent.OutputTuple,
      FullAccessPurchasedEvent.OutputObject
    >;
    FullAccessPurchased: TypedContractEvent<
      FullAccessPurchasedEvent.InputTuple,
      FullAccessPurchasedEvent.OutputTuple,
      FullAccessPurchasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceUpdated(uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "RegistrarUpdated(address)": TypedContractEvent<
      RegistrarUpdatedEvent.InputTuple,
      RegistrarUpdatedEvent.OutputTuple,
      RegistrarUpdatedEvent.OutputObject
    >;
    RegistrarUpdated: TypedContractEvent<
      RegistrarUpdatedEvent.InputTuple,
      RegistrarUpdatedEvent.OutputTuple,
      RegistrarUpdatedEvent.OutputObject
    >;

    "SGDDeactivated(uint256)": TypedContractEvent<
      SGDDeactivatedEvent.InputTuple,
      SGDDeactivatedEvent.OutputTuple,
      SGDDeactivatedEvent.OutputObject
    >;
    SGDDeactivated: TypedContractEvent<
      SGDDeactivatedEvent.InputTuple,
      SGDDeactivatedEvent.OutputTuple,
      SGDDeactivatedEvent.OutputObject
    >;

    "SGDRegistered(uint256,address,string,string,uint256)": TypedContractEvent<
      SGDRegisteredEvent.InputTuple,
      SGDRegisteredEvent.OutputTuple,
      SGDRegisteredEvent.OutputObject
    >;
    SGDRegistered: TypedContractEvent<
      SGDRegisteredEvent.InputTuple,
      SGDRegisteredEvent.OutputTuple,
      SGDRegisteredEvent.OutputObject
    >;
  };
}
