/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace GDMRegistry {
  export type SGDRecordStruct = {
    tokenId: BigNumberish;
    sgdId: string;
    rgdTokenId: BigNumberish;
    cid: string;
    registeredOwner: AddressLike;
    accessCondition: string;
    price: BigNumberish;
    collectionDate: BigNumberish;
    sampleType: string;
    patientRef: string;
    consentCode: string;
    sampleHash: string;
    encryptionScheme: string;
    sequencingInfo: string;
    signatureRef: string;
    encHash: string;
    createdAt: BigNumberish;
    active: boolean;
    version: BigNumberish;
  };

  export type SGDRecordStructOutput = [
    tokenId: bigint,
    sgdId: string,
    rgdTokenId: bigint,
    cid: string,
    registeredOwner: string,
    accessCondition: string,
    price: bigint,
    collectionDate: bigint,
    sampleType: string,
    patientRef: string,
    consentCode: string,
    sampleHash: string,
    encryptionScheme: string,
    sequencingInfo: string,
    signatureRef: string,
    encHash: string,
    createdAt: bigint,
    active: boolean,
    version: bigint
  ] & {
    tokenId: bigint;
    sgdId: string;
    rgdTokenId: bigint;
    cid: string;
    registeredOwner: string;
    accessCondition: string;
    price: bigint;
    collectionDate: bigint;
    sampleType: string;
    patientRef: string;
    consentCode: string;
    sampleHash: string;
    encryptionScheme: string;
    sequencingInfo: string;
    signatureRef: string;
    encHash: string;
    createdAt: bigint;
    active: boolean;
    version: bigint;
  };

  export type PublicRecordStruct = {
    tokenId: BigNumberish;
    sgdId: string;
    rgdTokenId: BigNumberish;
    currentOwner: AddressLike;
    accessCondition: string;
    price: BigNumberish;
    collectionDate: BigNumberish;
    sampleType: string;
    patientRef: string;
    consentCode: string;
    sampleHash: string;
    encryptionScheme: string;
    sequencingInfo: string;
    active: boolean;
  };

  export type PublicRecordStructOutput = [
    tokenId: bigint,
    sgdId: string,
    rgdTokenId: bigint,
    currentOwner: string,
    accessCondition: string,
    price: bigint,
    collectionDate: bigint,
    sampleType: string,
    patientRef: string,
    consentCode: string,
    sampleHash: string,
    encryptionScheme: string,
    sequencingInfo: string,
    active: boolean
  ] & {
    tokenId: bigint;
    sgdId: string;
    rgdTokenId: bigint;
    currentOwner: string;
    accessCondition: string;
    price: bigint;
    collectionDate: bigint;
    sampleType: string;
    patientRef: string;
    consentCode: string;
    sampleHash: string;
    encryptionScheme: string;
    sequencingInfo: string;
    active: boolean;
  };

  export type RegisterInputStruct = {
    initialOwner: AddressLike;
    sgdId: string;
    rgdTokenId: BigNumberish;
    cid: string;
    accessCondition: string;
    price: BigNumberish;
    collectionDate: BigNumberish;
    sampleType: string;
    patientRef: string;
    consentCode: string;
    sampleHash: string;
    encryptionScheme: string;
    sequencingInfo: string;
    signatureRef: string;
    encHash: string;
    tokenURI: string;
  };

  export type RegisterInputStructOutput = [
    initialOwner: string,
    sgdId: string,
    rgdTokenId: bigint,
    cid: string,
    accessCondition: string,
    price: bigint,
    collectionDate: bigint,
    sampleType: string,
    patientRef: string,
    consentCode: string,
    sampleHash: string,
    encryptionScheme: string,
    sequencingInfo: string,
    signatureRef: string,
    encHash: string,
    tokenURI: string
  ] & {
    initialOwner: string;
    sgdId: string;
    rgdTokenId: bigint;
    cid: string;
    accessCondition: string;
    price: bigint;
    collectionDate: bigint;
    sampleType: string;
    patientRef: string;
    consentCode: string;
    sampleHash: string;
    encryptionScheme: string;
    sequencingInfo: string;
    signatureRef: string;
    encHash: string;
    tokenURI: string;
  };
}

export interface GDMRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activateSGD"
      | "deactivateSGD"
      | "feeReceiver"
      | "getCID"
      | "getFullRecord"
      | "getPipelineStatus"
      | "getPublicRecord"
      | "getVersionsOfSgd"
      | "hasPurchased"
      | "isLatestVersion"
      | "isSGDPurchasable"
      | "latestTokenBySgdId"
      | "nextTokenId"
      | "onERC721Received"
      | "owner"
      | "platformFeePercentage"
      | "purchaseFullAccess"
      | "registerSGD"
      | "registrar"
      | "renounceOwnership"
      | "rgdOriginalOwners"
      | "setFeeConfiguration"
      | "setRegistrar"
      | "sgdNft"
      | "tacoCanDecrypt"
      | "transferOwnership"
      | "updateSGDVersion"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FullAccessPurchased"
      | "LatestVersionUpdated"
      | "OwnershipTransferred"
      | "RGDReceived"
      | "RegistrarUpdated"
      | "SGDDeactivated"
      | "SGDRegistered"
      | "SGDVersionUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activateSGD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateSGD",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCID",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFullRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPipelineStatus",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVersionsOfSgd",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPurchased",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isLatestVersion",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isSGDPurchasable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "latestTokenBySgdId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseFullAccess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSGD",
    values: [GDMRegistry.RegisterInputStruct]
  ): string;
  encodeFunctionData(functionFragment: "registrar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rgdOriginalOwners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeConfiguration",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistrar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "sgdNft", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tacoCanDecrypt",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSGDVersion",
    values: [BigNumberish, string, string, BigNumberish, string, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activateSGD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateSGD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFullRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPipelineStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVersionsOfSgd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isLatestVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSGDPurchasable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestTokenBySgdId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseFullAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSGD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registrar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rgdOriginalOwners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sgdNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tacoCanDecrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSGDVersion",
    data: BytesLike
  ): Result;
}

export namespace FullAccessPurchasedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, buyer: string, amount: bigint];
  export interface OutputObject {
    tokenId: bigint;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LatestVersionUpdatedEvent {
  export type InputTuple = [sgdId: string, latestTokenId: BigNumberish];
  export type OutputTuple = [sgdId: string, latestTokenId: bigint];
  export interface OutputObject {
    sgdId: string;
    latestTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RGDReceivedEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    tokenId: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    tokenId: bigint,
    data: string
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    tokenId: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistrarUpdatedEvent {
  export type InputTuple = [newRegistrar: AddressLike];
  export type OutputTuple = [newRegistrar: string];
  export interface OutputObject {
    newRegistrar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SGDDeactivatedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SGDRegisteredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    initialOwner: AddressLike,
    sgdId: string,
    cid: string,
    price: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    initialOwner: string,
    sgdId: string,
    cid: string,
    price: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    initialOwner: string;
    sgdId: string;
    cid: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SGDVersionUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    sgdId: string,
    newAccessCondition: string,
    newPrice: BigNumberish,
    newVersion: BigNumberish,
    newOwner: AddressLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    sgdId: string,
    newAccessCondition: string,
    newPrice: bigint,
    newVersion: bigint,
    newOwner: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    sgdId: string;
    newAccessCondition: string;
    newPrice: bigint;
    newVersion: bigint;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GDMRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): GDMRegistry;
  waitForDeployment(): Promise<this>;

  interface: GDMRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activateSGD: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  deactivateSGD: TypedContractMethod<
    [tokenId: BigNumberish, newWalletForActivation: AddressLike],
    [void],
    "nonpayable"
  >;

  feeReceiver: TypedContractMethod<[], [string], "view">;

  getCID: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getFullRecord: TypedContractMethod<
    [tokenId: BigNumberish],
    [GDMRegistry.SGDRecordStructOutput],
    "view"
  >;

  getPipelineStatus: TypedContractMethod<
    [rgdTokenId: BigNumberish, sequencingInfo: string],
    [bigint],
    "view"
  >;

  getPublicRecord: TypedContractMethod<
    [tokenId: BigNumberish],
    [GDMRegistry.PublicRecordStructOutput],
    "view"
  >;

  getVersionsOfSgd: TypedContractMethod<
    [tokenId: BigNumberish],
    [GDMRegistry.SGDRecordStructOutput[]],
    "view"
  >;

  hasPurchased: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isLatestVersion: TypedContractMethod<
    [tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  isSGDPurchasable: TypedContractMethod<[sgdId: string], [boolean], "view">;

  latestTokenBySgdId: TypedContractMethod<[arg0: string], [bigint], "view">;

  nextTokenId: TypedContractMethod<[], [bigint], "view">;

  onERC721Received: TypedContractMethod<
    [
      operator: AddressLike,
      from: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeePercentage: TypedContractMethod<[], [bigint], "view">;

  purchaseFullAccess: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "payable"
  >;

  registerSGD: TypedContractMethod<
    [input: GDMRegistry.RegisterInputStruct],
    [bigint],
    "nonpayable"
  >;

  registrar: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rgdOriginalOwners: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  setFeeConfiguration: TypedContractMethod<
    [newFeePercentage: BigNumberish, newFeeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  setRegistrar: TypedContractMethod<
    [newRegistrar: AddressLike],
    [void],
    "nonpayable"
  >;

  sgdNft: TypedContractMethod<[], [string], "view">;

  tacoCanDecrypt: TypedContractMethod<
    [tokenId: BigNumberish, buyer: AddressLike],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateSGDVersion: TypedContractMethod<
    [
      tokenId: BigNumberish,
      newCid: string,
      newAccessCondition: string,
      newPrice: BigNumberish,
      newTokenURI: string,
      newOwner: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activateSGD"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateSGD"
  ): TypedContractMethod<
    [tokenId: BigNumberish, newWalletForActivation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCID"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getFullRecord"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [GDMRegistry.SGDRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPipelineStatus"
  ): TypedContractMethod<
    [rgdTokenId: BigNumberish, sequencingInfo: string],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPublicRecord"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [GDMRegistry.PublicRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVersionsOfSgd"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [GDMRegistry.SGDRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPurchased"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isLatestVersion"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSGDPurchasable"
  ): TypedContractMethod<[sgdId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "latestTokenBySgdId"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextTokenId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [
      operator: AddressLike,
      from: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchaseFullAccess"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "registerSGD"
  ): TypedContractMethod<
    [input: GDMRegistry.RegisterInputStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registrar"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rgdOriginalOwners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "setFeeConfiguration"
  ): TypedContractMethod<
    [newFeePercentage: BigNumberish, newFeeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRegistrar"
  ): TypedContractMethod<[newRegistrar: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sgdNft"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tacoCanDecrypt"
  ): TypedContractMethod<
    [tokenId: BigNumberish, buyer: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSGDVersion"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      newCid: string,
      newAccessCondition: string,
      newPrice: BigNumberish,
      newTokenURI: string,
      newOwner: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FullAccessPurchased"
  ): TypedContractEvent<
    FullAccessPurchasedEvent.InputTuple,
    FullAccessPurchasedEvent.OutputTuple,
    FullAccessPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "LatestVersionUpdated"
  ): TypedContractEvent<
    LatestVersionUpdatedEvent.InputTuple,
    LatestVersionUpdatedEvent.OutputTuple,
    LatestVersionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RGDReceived"
  ): TypedContractEvent<
    RGDReceivedEvent.InputTuple,
    RGDReceivedEvent.OutputTuple,
    RGDReceivedEvent.OutputObject
  >;
  getEvent(
    key: "RegistrarUpdated"
  ): TypedContractEvent<
    RegistrarUpdatedEvent.InputTuple,
    RegistrarUpdatedEvent.OutputTuple,
    RegistrarUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SGDDeactivated"
  ): TypedContractEvent<
    SGDDeactivatedEvent.InputTuple,
    SGDDeactivatedEvent.OutputTuple,
    SGDDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "SGDRegistered"
  ): TypedContractEvent<
    SGDRegisteredEvent.InputTuple,
    SGDRegisteredEvent.OutputTuple,
    SGDRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "SGDVersionUpdated"
  ): TypedContractEvent<
    SGDVersionUpdatedEvent.InputTuple,
    SGDVersionUpdatedEvent.OutputTuple,
    SGDVersionUpdatedEvent.OutputObject
  >;

  filters: {
    "FullAccessPurchased(uint256,address,uint256)": TypedContractEvent<
      FullAccessPurchasedEvent.InputTuple,
      FullAccessPurchasedEvent.OutputTuple,
      FullAccessPurchasedEvent.OutputObject
    >;
    FullAccessPurchased: TypedContractEvent<
      FullAccessPurchasedEvent.InputTuple,
      FullAccessPurchasedEvent.OutputTuple,
      FullAccessPurchasedEvent.OutputObject
    >;

    "LatestVersionUpdated(string,uint256)": TypedContractEvent<
      LatestVersionUpdatedEvent.InputTuple,
      LatestVersionUpdatedEvent.OutputTuple,
      LatestVersionUpdatedEvent.OutputObject
    >;
    LatestVersionUpdated: TypedContractEvent<
      LatestVersionUpdatedEvent.InputTuple,
      LatestVersionUpdatedEvent.OutputTuple,
      LatestVersionUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RGDReceived(address,address,uint256,bytes)": TypedContractEvent<
      RGDReceivedEvent.InputTuple,
      RGDReceivedEvent.OutputTuple,
      RGDReceivedEvent.OutputObject
    >;
    RGDReceived: TypedContractEvent<
      RGDReceivedEvent.InputTuple,
      RGDReceivedEvent.OutputTuple,
      RGDReceivedEvent.OutputObject
    >;

    "RegistrarUpdated(address)": TypedContractEvent<
      RegistrarUpdatedEvent.InputTuple,
      RegistrarUpdatedEvent.OutputTuple,
      RegistrarUpdatedEvent.OutputObject
    >;
    RegistrarUpdated: TypedContractEvent<
      RegistrarUpdatedEvent.InputTuple,
      RegistrarUpdatedEvent.OutputTuple,
      RegistrarUpdatedEvent.OutputObject
    >;

    "SGDDeactivated(uint256)": TypedContractEvent<
      SGDDeactivatedEvent.InputTuple,
      SGDDeactivatedEvent.OutputTuple,
      SGDDeactivatedEvent.OutputObject
    >;
    SGDDeactivated: TypedContractEvent<
      SGDDeactivatedEvent.InputTuple,
      SGDDeactivatedEvent.OutputTuple,
      SGDDeactivatedEvent.OutputObject
    >;

    "SGDRegistered(uint256,address,string,string,uint256)": TypedContractEvent<
      SGDRegisteredEvent.InputTuple,
      SGDRegisteredEvent.OutputTuple,
      SGDRegisteredEvent.OutputObject
    >;
    SGDRegistered: TypedContractEvent<
      SGDRegisteredEvent.InputTuple,
      SGDRegisteredEvent.OutputTuple,
      SGDRegisteredEvent.OutputObject
    >;

    "SGDVersionUpdated(uint256,string,string,uint256,uint256,address)": TypedContractEvent<
      SGDVersionUpdatedEvent.InputTuple,
      SGDVersionUpdatedEvent.OutputTuple,
      SGDVersionUpdatedEvent.OutputObject
    >;
    SGDVersionUpdated: TypedContractEvent<
      SGDVersionUpdatedEvent.InputTuple,
      SGDVersionUpdatedEvent.OutputTuple,
      SGDVersionUpdatedEvent.OutputObject
    >;
  };
}
